#!/usr/bin/env perl
our $VERSION = "0.03";
use strict;
use warnings;
use App::lms;
App::lms->new->run(@ARGV);

=encoding utf-8

=head1 NAME

lms - Let Me See command

=head1 VERSION

Version 0.03

=head1 SYNOPSIS

lms command/library

=head1 DESCRIPTION

This is a small program to look a command or library file.

Only Perl is supported now.

=head1 INSTALL

cpanm https://github.com/kaz-utashiro/App-lms.git

=head1 SEE ALSO

L<App::optex>, L<https://github.com/kaz-utashiro/optex>

=head1 AUTHOR

Kazumasa Utashiro

=head1 LICENSE

Copyright 1992- Kazumasa Utashiro.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
