#!/usr/bin/env perl
our $VERSION = "0.09";
use strict;
use warnings;
use App::lms;

exit App::lms->new->run(splice @ARGV);

=encoding utf-8

=head1 NAME

lms - Let Me See command

=head1 VERSION

Version 0.09

=head1 SYNOPSIS

lms command/library

=head1 DESCRIPTION

This is a small program to look a command or library file.

It is convenient to see a command file written in shell or any other
script language.

As for library files, only Perl is supported, and experimental support
for Python is included.

=head1 OPTIONS

=over 7

=item B<-l>

Print module path.  Use multple times (C<-ll>) to call C<ls -l>.

=back

=head1 MODULES

=over 7

=item <App::lms::Command>

Module for executable file.

=item <App::lms::Perl>

Module for Perl module file.

=item <App::lms::Python>

Module for Python library file.  Use L<Inline> module to execute
Phthon script within Perl module.

=back

=head1 FILES

=over 7

=item F<~/.Inline>

Directory used by L<Inline> module.  Automatically created if not
exists.

=back

=head1 INSTALL

cpanm https://github.com/kaz-utashiro/App-lms.git

=head1 AUTHOR

Kazumasa Utashiro

=head1 LICENSE

Copyright 1992- Kazumasa Utashiro.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
